-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgK0GD/uPKTWL6zkEZ
YnFfEWP/SgcKcHyNWjbaaJxTimqgCgYIKoZIzj0DAQehRANCAASZL6d3sN/2lZ82
QMETw2A4YtIypVk8ruP7+zq0ZU+3y22bJcGXetYrofvxKjrtKuHhW2K9WW5WJqvT
5ljvRGHa
-----END PRIVATE KEY-----